import 'package:flutter/material.dart';
import 'models/word_entry.dart';
import 'services/word_database.dart';
import 'features/vocabulary_library/pages/vocabulary_review_page.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(theme:ThemeData(colorSchemeSeed:Colors.indigo),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{final store=WordDatabase.instance,search=TextEditingController();List<WordEntry> words=[];int count=1;bool loading=true;
 @override void initState(){super.initState();load();}Future<void> load()async{words=await store.all();if(mounted)setState(()=>loading=false);}Future<void> edit([WordEntry? w])async{final e=TextEditingController(text:w?.english),z=TextEditingController(text:w?.chinese);await showDialog(context:context,builder:(c)=>AlertDialog(title:Text(w==null?'新增词汇':'编辑词汇'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:e,decoration:const InputDecoration(labelText:'英文')),TextField(controller:z,decoration:const InputDecoration(labelText:'中文'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('取消')),FilledButton(onPressed:()async{if(e.text.trim().isEmpty||z.text.trim().isEmpty)return;await store.save(WordEntry(id:w?.id,english:e.text.trim(),chinese:z.text.trim()));if(c.mounted)Navigator.pop(c);await load();},child:const Text('保存'))]));}
 @override void dispose(){search.dispose();super.dispose();}@override Widget build(BuildContext c){final q=search.text.toLowerCase(),list=words.where((w)=>('${w.english}${w.chinese}').toLowerCase().contains(q)).toList(),max=words.isEmpty?1:words.length;if(count>max)count=max;return Scaffold(appBar:AppBar(title:const Text('词汇库'),actions:[IconButton(onPressed:edit,icon:const Icon(Icons.add))]),body:loading?const Center(child:CircularProgressIndicator()):Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'搜索英文或中文')),Text('词汇 ${words.length} 个 · 显示 ${list.length} 个'),Expanded(child:ListView.builder(itemCount:list.length,itemBuilder:(_,i){final w=list[i];return ListTile(title:Text(w.english),subtitle:Text(w.chinese),onTap:()=>edit(w),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{await store.remove(w.id!);load();}));})),if(words.isNotEmpty)...[Text('本次测试：$count 题'),Slider(value:count.toDouble(),min:1,max:max.toDouble(),divisions:max-1,onChanged:(v)=>setState(()=>count=v.round())),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>VocabularyReviewPage(words:words,count:count))),child:const Text('开始测试'))]else const Text('请先新增至少一个词汇')]))) ;}
}
